// Do not edit this file!
// The content are generated automatically
/* eslint-disable */

import '@busy-hour/blaze';
import type {
  ActionsExtractor,
  EventsExtractor,
  TrpcMutationExtractor,
  TrpcQueryExtractor
} from '@busy-hour/blaze-types/internal';
import core from '../services/core';
import users from '../services/users';

declare module '@busy-hour/blaze' {
  export interface ActionCallRecord extends 
    ActionsExtractor<typeof core>,
    ActionsExtractor<typeof users> {}

  export interface EventCallRecord extends 
    EventsExtractor<typeof core>,
    EventsExtractor<typeof users> {}

  export interface TrpcQueryCallRecord extends 
    TrpcQueryExtractor<typeof core>,
    TrpcQueryExtractor<typeof users> {}

  export interface TrpcMutationCallRecord extends 
    TrpcMutationExtractor<typeof core>,
    TrpcMutationExtractor<typeof users> {}
}
